### ISSUE TITLE
script needs reference to voevent-parse

### ISSUE THREAD

**Issue by caseyjlaw** [ebpetroff/FRB_VOEvent#1]
We are starting to implement this for realfast. I noticed that the script for generating a voevent refers to an object `vp`, but that is not defined in the script.
I'm guessing it should import from voevent-parse: https://voevent-parse.readthedocs.io/en/stable/ in the script.

**Comment by ebpetroff** [comment]
The script has now been updated to import all packages globally, this should fix the issue. A new version of the script is now available.
